package nju.sofware.data.dataobject;

public class TeamMember {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team_member.id
     *
     * @mbg.generated Wed Jul 10 21:19:09 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team_member.username
     *
     * @mbg.generated Wed Jul 10 21:19:09 CST 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team_member.name
     *
     * @mbg.generated Wed Jul 10 21:19:09 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team_member.sex
     *
     * @mbg.generated Wed Jul 10 21:19:09 CST 2019
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team_member.teamname
     *
     * @mbg.generated Wed Jul 10 21:19:09 CST 2019
     */
    private String teamname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team_member.teamrole
     *
     * @mbg.generated Wed Jul 10 21:19:09 CST 2019
     */
    private String teamrole;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team_member.phone
     *
     * @mbg.generated Wed Jul 10 21:19:09 CST 2019
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team_member.email
     *
     * @mbg.generated Wed Jul 10 21:19:09 CST 2019
     */
    private String email;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team_member.id
     *
     * @return the value of team_member.id
     *
     * @mbg.generated Wed Jul 10 21:19:09 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team_member.id
     *
     * @param id the value for team_member.id
     *
     * @mbg.generated Wed Jul 10 21:19:09 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team_member.username
     *
     * @return the value of team_member.username
     *
     * @mbg.generated Wed Jul 10 21:19:09 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team_member.username
     *
     * @param username the value for team_member.username
     *
     * @mbg.generated Wed Jul 10 21:19:09 CST 2019
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team_member.name
     *
     * @return the value of team_member.name
     *
     * @mbg.generated Wed Jul 10 21:19:09 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team_member.name
     *
     * @param name the value for team_member.name
     *
     * @mbg.generated Wed Jul 10 21:19:09 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team_member.sex
     *
     * @return the value of team_member.sex
     *
     * @mbg.generated Wed Jul 10 21:19:09 CST 2019
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team_member.sex
     *
     * @param sex the value for team_member.sex
     *
     * @mbg.generated Wed Jul 10 21:19:09 CST 2019
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team_member.teamname
     *
     * @return the value of team_member.teamname
     *
     * @mbg.generated Wed Jul 10 21:19:09 CST 2019
     */
    public String getTeamname() {
        return teamname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team_member.teamname
     *
     * @param teamname the value for team_member.teamname
     *
     * @mbg.generated Wed Jul 10 21:19:09 CST 2019
     */
    public void setTeamname(String teamname) {
        this.teamname = teamname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team_member.teamrole
     *
     * @return the value of team_member.teamrole
     *
     * @mbg.generated Wed Jul 10 21:19:09 CST 2019
     */
    public String getTeamrole() {
        return teamrole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team_member.teamrole
     *
     * @param teamrole the value for team_member.teamrole
     *
     * @mbg.generated Wed Jul 10 21:19:09 CST 2019
     */
    public void setTeamrole(String teamrole) {
        this.teamrole = teamrole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team_member.phone
     *
     * @return the value of team_member.phone
     *
     * @mbg.generated Wed Jul 10 21:19:09 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team_member.phone
     *
     * @param phone the value for team_member.phone
     *
     * @mbg.generated Wed Jul 10 21:19:09 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team_member.email
     *
     * @return the value of team_member.email
     *
     * @mbg.generated Wed Jul 10 21:19:09 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team_member.email
     *
     * @param email the value for team_member.email
     *
     * @mbg.generated Wed Jul 10 21:19:09 CST 2019
     */
    public void setEmail(String email) {
        this.email = email;
    }
}