package nju.sofware.data.dataobject;

public class Teaminfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teaminfo.id
     *
     * @mbg.generated Wed Jul 10 21:15:20 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teaminfo.teamname
     *
     * @mbg.generated Wed Jul 10 21:15:20 CST 2019
     */
    private String teamname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teaminfo.leadername
     *
     * @mbg.generated Wed Jul 10 21:15:20 CST 2019
     */
    private String leadername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teaminfo.leaderphone
     *
     * @mbg.generated Wed Jul 10 21:15:20 CST 2019
     */
    private String leaderphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teaminfo.leaderemail
     *
     * @mbg.generated Wed Jul 10 21:15:20 CST 2019
     */
    private String leaderemail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teaminfo.id
     *
     * @return the value of teaminfo.id
     *
     * @mbg.generated Wed Jul 10 21:15:20 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teaminfo.id
     *
     * @param id the value for teaminfo.id
     *
     * @mbg.generated Wed Jul 10 21:15:20 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teaminfo.teamname
     *
     * @return the value of teaminfo.teamname
     *
     * @mbg.generated Wed Jul 10 21:15:20 CST 2019
     */
    public String getTeamname() {
        return teamname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teaminfo.teamname
     *
     * @param teamname the value for teaminfo.teamname
     *
     * @mbg.generated Wed Jul 10 21:15:20 CST 2019
     */
    public void setTeamname(String teamname) {
        this.teamname = teamname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teaminfo.leadername
     *
     * @return the value of teaminfo.leadername
     *
     * @mbg.generated Wed Jul 10 21:15:20 CST 2019
     */
    public String getLeadername() {
        return leadername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teaminfo.leadername
     *
     * @param leadername the value for teaminfo.leadername
     *
     * @mbg.generated Wed Jul 10 21:15:20 CST 2019
     */
    public void setLeadername(String leadername) {
        this.leadername = leadername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teaminfo.leaderphone
     *
     * @return the value of teaminfo.leaderphone
     *
     * @mbg.generated Wed Jul 10 21:15:20 CST 2019
     */
    public String getLeaderphone() {
        return leaderphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teaminfo.leaderphone
     *
     * @param leaderphone the value for teaminfo.leaderphone
     *
     * @mbg.generated Wed Jul 10 21:15:20 CST 2019
     */
    public void setLeaderphone(String leaderphone) {
        this.leaderphone = leaderphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teaminfo.leaderemail
     *
     * @return the value of teaminfo.leaderemail
     *
     * @mbg.generated Wed Jul 10 21:15:20 CST 2019
     */
    public String getLeaderemail() {
        return leaderemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teaminfo.leaderemail
     *
     * @param leaderemail the value for teaminfo.leaderemail
     *
     * @mbg.generated Wed Jul 10 21:15:20 CST 2019
     */
    public void setLeaderemail(String leaderemail) {
        this.leaderemail = leaderemail;
    }
}