package nju.sofware.data.dataobject;

public class Ucustomer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ucustomer.customerid
     *
     * @mbg.generated Sun Jul 14 14:47:12 CST 2019
     */
    private Integer customerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ucustomer.customerbriefname
     *
     * @mbg.generated Sun Jul 14 14:47:12 CST 2019
     */
    private String customerbriefname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ucustomer.customerfullname
     *
     * @mbg.generated Sun Jul 14 14:47:12 CST 2019
     */
    private String customerfullname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ucustomer.customerid
     *
     * @return the value of ucustomer.customerid
     *
     * @mbg.generated Sun Jul 14 14:47:12 CST 2019
     */
    public Integer getCustomerid() {
        return customerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ucustomer.customerid
     *
     * @param customerid the value for ucustomer.customerid
     *
     * @mbg.generated Sun Jul 14 14:47:12 CST 2019
     */
    public void setCustomerid(Integer customerid) {
        this.customerid = customerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ucustomer.customerbriefname
     *
     * @return the value of ucustomer.customerbriefname
     *
     * @mbg.generated Sun Jul 14 14:47:12 CST 2019
     */
    public String getCustomerbriefname() {
        return customerbriefname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ucustomer.customerbriefname
     *
     * @param customerbriefname the value for ucustomer.customerbriefname
     *
     * @mbg.generated Sun Jul 14 14:47:12 CST 2019
     */
    public void setCustomerbriefname(String customerbriefname) {
        this.customerbriefname = customerbriefname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ucustomer.customerfullname
     *
     * @return the value of ucustomer.customerfullname
     *
     * @mbg.generated Sun Jul 14 14:47:12 CST 2019
     */
    public String getCustomerfullname() {
        return customerfullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ucustomer.customerfullname
     *
     * @param customerfullname the value for ucustomer.customerfullname
     *
     * @mbg.generated Sun Jul 14 14:47:12 CST 2019
     */
    public void setCustomerfullname(String customerfullname) {
        this.customerfullname = customerfullname;
    }
}