package nju.sofware.data.dataobject;

public class Userinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.id
     *
     * @mbg.generated Wed Jul 10 17:14:07 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.username
     *
     * @mbg.generated Wed Jul 10 17:14:07 CST 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.name
     *
     * @mbg.generated Wed Jul 10 17:14:07 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.role
     *
     * @mbg.generated Wed Jul 10 17:14:07 CST 2019
     */
    private String role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.mode
     *
     * @mbg.generated Wed Jul 10 17:14:07 CST 2019
     */
    private String mode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.headimage
     *
     * @mbg.generated Wed Jul 10 17:14:07 CST 2019
     */
    private String headimage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.id
     *
     * @return the value of userinfo.id
     *
     * @mbg.generated Wed Jul 10 17:14:07 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.id
     *
     * @param id the value for userinfo.id
     *
     * @mbg.generated Wed Jul 10 17:14:07 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.username
     *
     * @return the value of userinfo.username
     *
     * @mbg.generated Wed Jul 10 17:14:07 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.username
     *
     * @param username the value for userinfo.username
     *
     * @mbg.generated Wed Jul 10 17:14:07 CST 2019
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.name
     *
     * @return the value of userinfo.name
     *
     * @mbg.generated Wed Jul 10 17:14:07 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.name
     *
     * @param name the value for userinfo.name
     *
     * @mbg.generated Wed Jul 10 17:14:07 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.role
     *
     * @return the value of userinfo.role
     *
     * @mbg.generated Wed Jul 10 17:14:07 CST 2019
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.role
     *
     * @param role the value for userinfo.role
     *
     * @mbg.generated Wed Jul 10 17:14:07 CST 2019
     */
    public void setRole(String role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.mode
     *
     * @return the value of userinfo.mode
     *
     * @mbg.generated Wed Jul 10 17:14:07 CST 2019
     */
    public String getMode() {
        return mode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.mode
     *
     * @param mode the value for userinfo.mode
     *
     * @mbg.generated Wed Jul 10 17:14:07 CST 2019
     */
    public void setMode(String mode) {
        this.mode = mode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.headimage
     *
     * @return the value of userinfo.headimage
     *
     * @mbg.generated Wed Jul 10 17:14:07 CST 2019
     */
    public String getHeadimage() {
        return headimage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.headimage
     *
     * @param headimage the value for userinfo.headimage
     *
     * @mbg.generated Wed Jul 10 17:14:07 CST 2019
     */
    public void setHeadimage(String headimage) {
        this.headimage = headimage;
    }
}