package nju.sofware.data.dataobject;

public class Useraccount {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column useraccount.username
	 * @mbg.generated  Sun Jul 14 08:55:57 CST 2019
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column useraccount.password
	 * @mbg.generated  Sun Jul 14 08:55:57 CST 2019
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column useraccount.phone
	 * @mbg.generated  Sun Jul 14 08:55:57 CST 2019
	 */
	private Integer phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column useraccount.email
	 * @mbg.generated  Sun Jul 14 08:55:57 CST 2019
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column useraccount.power
	 * @mbg.generated  Sun Jul 14 08:55:57 CST 2019
	 */
	private Integer power;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column useraccount.headimage
	 * @mbg.generated  Sun Jul 14 08:55:57 CST 2019
	 */
	private String headimage;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column useraccount.username
	 * @return  the value of useraccount.username
	 * @mbg.generated  Sun Jul 14 08:55:57 CST 2019
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column useraccount.username
	 * @param username  the value for useraccount.username
	 * @mbg.generated  Sun Jul 14 08:55:57 CST 2019
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column useraccount.password
	 * @return  the value of useraccount.password
	 * @mbg.generated  Sun Jul 14 08:55:57 CST 2019
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column useraccount.password
	 * @param password  the value for useraccount.password
	 * @mbg.generated  Sun Jul 14 08:55:57 CST 2019
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column useraccount.phone
	 * @return  the value of useraccount.phone
	 * @mbg.generated  Sun Jul 14 08:55:57 CST 2019
	 */
	public Integer getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column useraccount.phone
	 * @param phone  the value for useraccount.phone
	 * @mbg.generated  Sun Jul 14 08:55:57 CST 2019
	 */
	public void setPhone(Integer phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column useraccount.email
	 * @return  the value of useraccount.email
	 * @mbg.generated  Sun Jul 14 08:55:57 CST 2019
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column useraccount.email
	 * @param email  the value for useraccount.email
	 * @mbg.generated  Sun Jul 14 08:55:57 CST 2019
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column useraccount.power
	 * @return  the value of useraccount.power
	 * @mbg.generated  Sun Jul 14 08:55:57 CST 2019
	 */
	public Integer getPower() {
		return power;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column useraccount.power
	 * @param power  the value for useraccount.power
	 * @mbg.generated  Sun Jul 14 08:55:57 CST 2019
	 */
	public void setPower(Integer power) {
		this.power = power;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column useraccount.headimage
	 * @return  the value of useraccount.headimage
	 * @mbg.generated  Sun Jul 14 08:55:57 CST 2019
	 */
	public String getHeadimage() {
		return headimage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column useraccount.headimage
	 * @param headimage  the value for useraccount.headimage
	 * @mbg.generated  Sun Jul 14 08:55:57 CST 2019
	 */
	public void setHeadimage(String headimage) {
		this.headimage = headimage;
	}
}