package nju.sofware.data.dao;

import java.util.List;

import nju.sofware.data.dataobject.TeamMember;
import nju.sofware.data.dataobject.Teaminfo;
import nju.sofware.data.dataobject.TeaminfoExample;
import org.apache.ibatis.annotations.Param;

public interface TeaminfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teaminfo
     *
     * @mbg.generated Wed Jul 10 21:15:20 CST 2019
     */
    long countByExample(TeaminfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teaminfo
     *
     * @mbg.generated Wed Jul 10 21:15:20 CST 2019
     */
    int deleteByExample(TeaminfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teaminfo
     *
     * @mbg.generated Wed Jul 10 21:15:20 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teaminfo
     *
     * @mbg.generated Wed Jul 10 21:15:20 CST 2019
     */
    int insert(Teaminfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teaminfo
     *
     * @mbg.generated Wed Jul 10 21:15:20 CST 2019
     */
    int insertSelective(Teaminfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teaminfo
     *
     * @mbg.generated Wed Jul 10 21:15:20 CST 2019
     */
    List<Teaminfo> selectByExample(TeaminfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teaminfo
     *
     * @mbg.generated Wed Jul 10 21:15:20 CST 2019
     */
    Teaminfo selectByPrimaryKey(Integer id);
    /*
     * ≤È’“À˘”–
     * 2019/07/10
     * ¡ıÀ∂
     */
    List<Teaminfo> selectAll();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teaminfo
     *
     * @mbg.generated Wed Jul 10 21:15:20 CST 2019
     */
    int updateByExampleSelective(@Param("record") Teaminfo record, @Param("example") TeaminfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teaminfo
     *
     * @mbg.generated Wed Jul 10 21:15:20 CST 2019
     */
    int updateByExample(@Param("record") Teaminfo record, @Param("example") TeaminfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teaminfo
     *
     * @mbg.generated Wed Jul 10 21:15:20 CST 2019
     */
    int updateByPrimaryKeySelective(Teaminfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teaminfo
     *
     * @mbg.generated Wed Jul 10 21:15:20 CST 2019
     */
    int updateByPrimaryKey(Teaminfo record);
}