package nju.sofware.data.dao;

import java.util.List;
import nju.sofware.data.dataobject.TeamMember;
import nju.sofware.data.dataobject.TeamMemberExample;
import nju.sofware.data.dataobject.Userinfo;

import org.apache.ibatis.annotations.Param;

public interface TeamMemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_member
     *
     * @mbg.generated Wed Jul 10 21:19:09 CST 2019
     */
    long countByExample(TeamMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_member
     *
     * @mbg.generated Wed Jul 10 21:19:09 CST 2019
     */
    int deleteByExample(TeamMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_member
     *
     * @mbg.generated Wed Jul 10 21:19:09 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_member
     *
     * @mbg.generated Wed Jul 10 21:19:09 CST 2019
     */
    int insert(TeamMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_member
     *
     * @mbg.generated Wed Jul 10 21:19:09 CST 2019
     */
    int insertSelective(TeamMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_member
     *
     * @mbg.generated Wed Jul 10 21:19:09 CST 2019
     */
    List<TeamMember> selectByExample(TeamMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_member
     *
     * @mbg.generated Wed Jul 10 21:19:09 CST 2019
     */
    TeamMember selectByPrimaryKey(Integer id);
    /*
     * ≤È’“À˘”–
     * 2019/07/10
     * ¡ıÀ∂
     */
    List<TeamMember> selectAll();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_member
     *
     * @mbg.generated Wed Jul 10 21:19:09 CST 2019
     */
    int updateByExampleSelective(@Param("record") TeamMember record, @Param("example") TeamMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_member
     *
     * @mbg.generated Wed Jul 10 21:19:09 CST 2019
     */
    int updateByExample(@Param("record") TeamMember record, @Param("example") TeamMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_member
     *
     * @mbg.generated Wed Jul 10 21:19:09 CST 2019
     */
    int updateByPrimaryKeySelective(TeamMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_member
     *
     * @mbg.generated Wed Jul 10 21:19:09 CST 2019
     */
    int updateByPrimaryKey(TeamMember record);
}