package nju.sofware.data.dao;

import java.util.List;

import nju.sofware.data.dataobject.Teaminfo;
import nju.sofware.data.dataobject.Ucustomer;
import nju.sofware.data.dataobject.UcustomerExample;
import org.apache.ibatis.annotations.Param;

public interface UcustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ucustomer
     *
     * @mbg.generated Sun Jul 14 14:47:12 CST 2019
     */
    long countByExample(UcustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ucustomer
     *
     * @mbg.generated Sun Jul 14 14:47:12 CST 2019
     */
    int deleteByExample(UcustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ucustomer
     *
     * @mbg.generated Sun Jul 14 14:47:12 CST 2019
     */
    int deleteByPrimaryKey(Integer customerid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ucustomer
     *
     * @mbg.generated Sun Jul 14 14:47:12 CST 2019
     */
    int insert(Ucustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ucustomer
     *
     * @mbg.generated Sun Jul 14 14:47:12 CST 2019
     */
    int insertSelective(Ucustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ucustomer
     *
     * @mbg.generated Sun Jul 14 14:47:12 CST 2019
     */
    List<Ucustomer> selectByExample(UcustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ucustomer
     *
     * @mbg.generated Sun Jul 14 14:47:12 CST 2019
     */
    Ucustomer selectByPrimaryKey(Integer customerid);

    /*
     * ≤È’“À˘”–
     * 2019/07/14
     * ¡ıÀ∂
     */
    List<Ucustomer> selectAll();
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ucustomer
     *
     * @mbg.generated Sun Jul 14 14:47:12 CST 2019
     */
    int updateByExampleSelective(@Param("record") Ucustomer record, @Param("example") UcustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ucustomer
     *
     * @mbg.generated Sun Jul 14 14:47:12 CST 2019
     */
    int updateByExample(@Param("record") Ucustomer record, @Param("example") UcustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ucustomer
     *
     * @mbg.generated Sun Jul 14 14:47:12 CST 2019
     */
    int updateByPrimaryKeySelective(Ucustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ucustomer
     *
     * @mbg.generated Sun Jul 14 14:47:12 CST 2019
     */
    int updateByPrimaryKey(Ucustomer record);
}