package nju.sofware.data.dao;

import java.util.List;
import nju.sofware.data.dataobject.Useraccount;
import nju.sofware.data.dataobject.UseraccountExample;
import org.apache.ibatis.annotations.Param;

public interface UseraccountMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table useraccount
	 * @mbg.generated  Sun Jul 14 08:55:57 CST 2019
	 */
	long countByExample(UseraccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table useraccount
	 * @mbg.generated  Sun Jul 14 08:55:57 CST 2019
	 */
	int deleteByExample(UseraccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table useraccount
	 * @mbg.generated  Sun Jul 14 08:55:57 CST 2019
	 */
	int deleteByPrimaryKey(String username);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table useraccount
	 * @mbg.generated  Sun Jul 14 08:55:57 CST 2019
	 */
	int insert(Useraccount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table useraccount
	 * @mbg.generated  Sun Jul 14 08:55:57 CST 2019
	 */
	int insertSelective(Useraccount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table useraccount
	 * @mbg.generated  Sun Jul 14 08:55:57 CST 2019
	 */
	List<Useraccount> selectByExample(UseraccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table useraccount
	 * @mbg.generated  Sun Jul 14 08:55:57 CST 2019
	 */
	Useraccount selectByPrimaryKey(String username);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table useraccount
	 * @mbg.generated  Sun Jul 14 08:55:57 CST 2019
	 */
	int updateByExampleSelective(@Param("record") Useraccount record, @Param("example") UseraccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table useraccount
	 * @mbg.generated  Sun Jul 14 08:55:57 CST 2019
	 */
	int updateByExample(@Param("record") Useraccount record, @Param("example") UseraccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table useraccount
	 * @mbg.generated  Sun Jul 14 08:55:57 CST 2019
	 */
	int updateByPrimaryKeySelective(Useraccount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table useraccount
	 * @mbg.generated  Sun Jul 14 08:55:57 CST 2019
	 */
	int updateByPrimaryKey(Useraccount record);
	
	/**
	 * 当密码输入为空时，不更新密码
	 * 刘硕2019/07/14
	 */
	int updateByPrimaryKeywithoutPassword(Useraccount record);
}